spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: person_consumer_app
      auto-offset-reset: latest
    listener:
      concurrency: 3
    topic-name: person_topic

schema:
  registry:
    url: http://localhost:8081

logging:
  level:
    root: info

